# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/liquanyan/Desktop/OpenCV_CPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/liquanyan/Desktop/OpenCV_CPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liquanyan/Desktop/OpenCV_CPP/CMakeFiles /Users/liquanyan/Desktop/OpenCV_CPP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liquanyan/Desktop/OpenCV_CPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv.exe

# Build rule for target.
opencv.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv.exe
.PHONY : opencv.exe

# fast build rule for target.
opencv.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv.exe.dir/build.make CMakeFiles/opencv.exe.dir/build
.PHONY : opencv.exe/fast

#=============================================================================
# Target rules for targets named opencvtranslate.exe

# Build rule for target.
opencvtranslate.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencvtranslate.exe
.PHONY : opencvtranslate.exe

# fast build rule for target.
opencvtranslate.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvtranslate.exe.dir/build.make CMakeFiles/opencvtranslate.exe.dir/build
.PHONY : opencvtranslate.exe/fast

#=============================================================================
# Target rules for targets named opencvdraw.exe

# Build rule for target.
opencvdraw.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencvdraw.exe
.PHONY : opencvdraw.exe

# fast build rule for target.
opencvdraw.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvdraw.exe.dir/build.make CMakeFiles/opencvdraw.exe.dir/build
.PHONY : opencvdraw.exe/fast

#=============================================================================
# Target rules for targets named opencvnoise.exe

# Build rule for target.
opencvnoise.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencvnoise.exe
.PHONY : opencvnoise.exe

# fast build rule for target.
opencvnoise.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoise.exe.dir/build.make CMakeFiles/opencvnoise.exe.dir/build
.PHONY : opencvnoise.exe/fast

#=============================================================================
# Target rules for targets named opencvnoisegaussian.exe

# Build rule for target.
opencvnoisegaussian.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencvnoisegaussian.exe
.PHONY : opencvnoisegaussian.exe

# fast build rule for target.
opencvnoisegaussian.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisegaussian.exe.dir/build.make CMakeFiles/opencvnoisegaussian.exe.dir/build
.PHONY : opencvnoisegaussian.exe/fast

#=============================================================================
# Target rules for targets named opencvnoisemedian.exe

# Build rule for target.
opencvnoisemedian.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencvnoisemedian.exe
.PHONY : opencvnoisemedian.exe

# fast build rule for target.
opencvnoisemedian.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisemedian.exe.dir/build.make CMakeFiles/opencvnoisemedian.exe.dir/build
.PHONY : opencvnoisemedian.exe/fast

src/opencv.o: src/opencv.cpp.o
.PHONY : src/opencv.o

# target to build an object file
src/opencv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv.exe.dir/build.make CMakeFiles/opencv.exe.dir/src/opencv.cpp.o
.PHONY : src/opencv.cpp.o

src/opencv.i: src/opencv.cpp.i
.PHONY : src/opencv.i

# target to preprocess a source file
src/opencv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv.exe.dir/build.make CMakeFiles/opencv.exe.dir/src/opencv.cpp.i
.PHONY : src/opencv.cpp.i

src/opencv.s: src/opencv.cpp.s
.PHONY : src/opencv.s

# target to generate assembly for a file
src/opencv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv.exe.dir/build.make CMakeFiles/opencv.exe.dir/src/opencv.cpp.s
.PHONY : src/opencv.cpp.s

src/opencvdraw.o: src/opencvdraw.cpp.o
.PHONY : src/opencvdraw.o

# target to build an object file
src/opencvdraw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvdraw.exe.dir/build.make CMakeFiles/opencvdraw.exe.dir/src/opencvdraw.cpp.o
.PHONY : src/opencvdraw.cpp.o

src/opencvdraw.i: src/opencvdraw.cpp.i
.PHONY : src/opencvdraw.i

# target to preprocess a source file
src/opencvdraw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvdraw.exe.dir/build.make CMakeFiles/opencvdraw.exe.dir/src/opencvdraw.cpp.i
.PHONY : src/opencvdraw.cpp.i

src/opencvdraw.s: src/opencvdraw.cpp.s
.PHONY : src/opencvdraw.s

# target to generate assembly for a file
src/opencvdraw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvdraw.exe.dir/build.make CMakeFiles/opencvdraw.exe.dir/src/opencvdraw.cpp.s
.PHONY : src/opencvdraw.cpp.s

src/opencvnoise/opencvnoiseBlur.o: src/opencvnoise/opencvnoiseBlur.cpp.o
.PHONY : src/opencvnoise/opencvnoiseBlur.o

# target to build an object file
src/opencvnoise/opencvnoiseBlur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoise.exe.dir/build.make CMakeFiles/opencvnoise.exe.dir/src/opencvnoise/opencvnoiseBlur.cpp.o
.PHONY : src/opencvnoise/opencvnoiseBlur.cpp.o

src/opencvnoise/opencvnoiseBlur.i: src/opencvnoise/opencvnoiseBlur.cpp.i
.PHONY : src/opencvnoise/opencvnoiseBlur.i

# target to preprocess a source file
src/opencvnoise/opencvnoiseBlur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoise.exe.dir/build.make CMakeFiles/opencvnoise.exe.dir/src/opencvnoise/opencvnoiseBlur.cpp.i
.PHONY : src/opencvnoise/opencvnoiseBlur.cpp.i

src/opencvnoise/opencvnoiseBlur.s: src/opencvnoise/opencvnoiseBlur.cpp.s
.PHONY : src/opencvnoise/opencvnoiseBlur.s

# target to generate assembly for a file
src/opencvnoise/opencvnoiseBlur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoise.exe.dir/build.make CMakeFiles/opencvnoise.exe.dir/src/opencvnoise/opencvnoiseBlur.cpp.s
.PHONY : src/opencvnoise/opencvnoiseBlur.cpp.s

src/opencvnoise/opencvnoiseGaussianBlur.o: src/opencvnoise/opencvnoiseGaussianBlur.cpp.o
.PHONY : src/opencvnoise/opencvnoiseGaussianBlur.o

# target to build an object file
src/opencvnoise/opencvnoiseGaussianBlur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisegaussian.exe.dir/build.make CMakeFiles/opencvnoisegaussian.exe.dir/src/opencvnoise/opencvnoiseGaussianBlur.cpp.o
.PHONY : src/opencvnoise/opencvnoiseGaussianBlur.cpp.o

src/opencvnoise/opencvnoiseGaussianBlur.i: src/opencvnoise/opencvnoiseGaussianBlur.cpp.i
.PHONY : src/opencvnoise/opencvnoiseGaussianBlur.i

# target to preprocess a source file
src/opencvnoise/opencvnoiseGaussianBlur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisegaussian.exe.dir/build.make CMakeFiles/opencvnoisegaussian.exe.dir/src/opencvnoise/opencvnoiseGaussianBlur.cpp.i
.PHONY : src/opencvnoise/opencvnoiseGaussianBlur.cpp.i

src/opencvnoise/opencvnoiseGaussianBlur.s: src/opencvnoise/opencvnoiseGaussianBlur.cpp.s
.PHONY : src/opencvnoise/opencvnoiseGaussianBlur.s

# target to generate assembly for a file
src/opencvnoise/opencvnoiseGaussianBlur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisegaussian.exe.dir/build.make CMakeFiles/opencvnoisegaussian.exe.dir/src/opencvnoise/opencvnoiseGaussianBlur.cpp.s
.PHONY : src/opencvnoise/opencvnoiseGaussianBlur.cpp.s

src/opencvnoise/opencvnoiseMedianBlur.o: src/opencvnoise/opencvnoiseMedianBlur.cpp.o
.PHONY : src/opencvnoise/opencvnoiseMedianBlur.o

# target to build an object file
src/opencvnoise/opencvnoiseMedianBlur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisemedian.exe.dir/build.make CMakeFiles/opencvnoisemedian.exe.dir/src/opencvnoise/opencvnoiseMedianBlur.cpp.o
.PHONY : src/opencvnoise/opencvnoiseMedianBlur.cpp.o

src/opencvnoise/opencvnoiseMedianBlur.i: src/opencvnoise/opencvnoiseMedianBlur.cpp.i
.PHONY : src/opencvnoise/opencvnoiseMedianBlur.i

# target to preprocess a source file
src/opencvnoise/opencvnoiseMedianBlur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisemedian.exe.dir/build.make CMakeFiles/opencvnoisemedian.exe.dir/src/opencvnoise/opencvnoiseMedianBlur.cpp.i
.PHONY : src/opencvnoise/opencvnoiseMedianBlur.cpp.i

src/opencvnoise/opencvnoiseMedianBlur.s: src/opencvnoise/opencvnoiseMedianBlur.cpp.s
.PHONY : src/opencvnoise/opencvnoiseMedianBlur.s

# target to generate assembly for a file
src/opencvnoise/opencvnoiseMedianBlur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvnoisemedian.exe.dir/build.make CMakeFiles/opencvnoisemedian.exe.dir/src/opencvnoise/opencvnoiseMedianBlur.cpp.s
.PHONY : src/opencvnoise/opencvnoiseMedianBlur.cpp.s

src/opencvtranslate.o: src/opencvtranslate.cpp.o
.PHONY : src/opencvtranslate.o

# target to build an object file
src/opencvtranslate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvtranslate.exe.dir/build.make CMakeFiles/opencvtranslate.exe.dir/src/opencvtranslate.cpp.o
.PHONY : src/opencvtranslate.cpp.o

src/opencvtranslate.i: src/opencvtranslate.cpp.i
.PHONY : src/opencvtranslate.i

# target to preprocess a source file
src/opencvtranslate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvtranslate.exe.dir/build.make CMakeFiles/opencvtranslate.exe.dir/src/opencvtranslate.cpp.i
.PHONY : src/opencvtranslate.cpp.i

src/opencvtranslate.s: src/opencvtranslate.cpp.s
.PHONY : src/opencvtranslate.s

# target to generate assembly for a file
src/opencvtranslate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencvtranslate.exe.dir/build.make CMakeFiles/opencvtranslate.exe.dir/src/opencvtranslate.cpp.s
.PHONY : src/opencvtranslate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... opencv.exe"
	@echo "... opencvdraw.exe"
	@echo "... opencvnoise.exe"
	@echo "... opencvnoisegaussian.exe"
	@echo "... opencvnoisemedian.exe"
	@echo "... opencvtranslate.exe"
	@echo "... src/opencv.o"
	@echo "... src/opencv.i"
	@echo "... src/opencv.s"
	@echo "... src/opencvdraw.o"
	@echo "... src/opencvdraw.i"
	@echo "... src/opencvdraw.s"
	@echo "... src/opencvnoise/opencvnoiseBlur.o"
	@echo "... src/opencvnoise/opencvnoiseBlur.i"
	@echo "... src/opencvnoise/opencvnoiseBlur.s"
	@echo "... src/opencvnoise/opencvnoiseGaussianBlur.o"
	@echo "... src/opencvnoise/opencvnoiseGaussianBlur.i"
	@echo "... src/opencvnoise/opencvnoiseGaussianBlur.s"
	@echo "... src/opencvnoise/opencvnoiseMedianBlur.o"
	@echo "... src/opencvnoise/opencvnoiseMedianBlur.i"
	@echo "... src/opencvnoise/opencvnoiseMedianBlur.s"
	@echo "... src/opencvtranslate.o"
	@echo "... src/opencvtranslate.i"
	@echo "... src/opencvtranslate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

